version: 0.2

phases:
  install:
    commands:
      - echo Updating package lists...
      - sudo apt-get update -y
      - echo Installing Nginx...
      - sudo apt-get install -y nginx
  pre_build:
    commands:
      - echo Starting Nginx service...
      - sudo systemctl start nginx
      - sudo systemctl enable nginx
  build:
    commands:
      - echo Copying index.html to /var/www/html/
      - sudo cp index.html /var/www/html/
  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - index.html
